- name: System Prepare
  hosts: all
  roles:
    - system_prepare
  tags:
    - always
    - system_prepare

- name: yay
  hosts: all
  roles:
    - yay
  tags:
    - always
    - yay

- name: Z Shell
  hosts: all
  roles:
    - zsh
  tags:
    - zsh

- name: Wake on LAN
  hosts: all
  roles:
    - wake_on_lan
  tags:
    - wake_on_lan

- name: SSH
  hosts: all
  roles:
    - ssh
  tags:
    - ssh

- name: Wayland
  hosts: all
  roles:
    - wayland
  tags:
    - wayland

- name: waybar
  hosts: all
  roles:
    - waybar
  tags:
    - waybar

- name: sway
  hosts: all
  roles:
    - sway
  tags:
    - sway

- name: playerctl
  hosts: all
  roles:
    - playerctl
  tags:
    - playerctl

- name: Appearance
  hosts: all
  roles:
    - appearance
  tags:
    - appearance

- name: rofi
  hosts: all
  roles:
    - rofi
  tags:
    - rofi

- name: foot
  hosts: all
  roles:
    - foot
  tags:
    - foot

- name: files_managers
  hosts: all
  roles:
    - files_managers
  tags:
    - files_managers

- name: Browsers
  hosts: all
  roles:
    - browsers
  tags:
    - browsers

- name: vim
  hosts: all
  roles:
    - vim
  tags:
    - vim

- name: VS Code
  hosts: all
  roles:
    - vscode
  tags:
    - vscode

- name: OpenCode
  hosts: all
  roles:
    - opencode
  tags:
    - opencode

- name: Syncthing
  hosts: all
  roles:
    - syncthing
  tags:
    - syncthing

- name: Bluetooth
  hosts: all
  roles:
    - bluetooth
  tags:
    - bluetooth

- name: Keyring
  hosts: all
  roles:
    - keyring
  tags:
    - keyring

- name: rclone (Google Drive)
  hosts: all
  roles:
    - rclone
  tags:
    - rclone

- name: Docker
  hosts: all
  roles:
    - docker
  tags:
    - docker

- name: NodeJS Lang
  hosts: all
  roles:
    - nodejs_lang
  tags:
    - nodejs_lang

- name: Elixir Lang
  hosts: all
  roles:
    - elixir_lang
  tags:
    - elixir_lang

- name: Android SDK
  hosts: all
  roles:
    - android_sdk
  tags:
    - android_sdk
    - android_emulator
  
- name: Android Emulator
  hosts: all
  roles:
    - android_emulator
  tags:
    - never
    - android_emulator

- name: VirtualBox
  hosts: all
  roles:
    - virtualbox
  tags:
    - virtualbox

- name: Embedded systems (Arduino, PlatformIO, ...)
  hosts: all
  roles:
    - embedded_systems
  tags:
    - embedded_systems

- name: DroidCam
  hosts: all
  roles:
    - droidcam
  tags:
    - droidcam

- name: Gimp
  hosts: all
  roles:
    - gimp
  tags:
    - gimp

- name: OBS
  hosts: all
  roles:
    - obs
  tags:
    - obs

- name: Wireshark
  hosts: all
  roles:
    - wireshark
  tags:
    - wireshark

- name: General Programs
  hosts: all
  roles:
    - general_programs
  tags:
    - general_programs
