- name: Installing VS Code
  kewlfft.aur.aur:
    use: yay
    name: visual-studio-code-bin
    state: latest
  become: True
  become_user: aur_builder

- name: Installing Fira Code Font
  pacman:
    name: ttf-fira-code
    state: latest
  become: True
