- name: Installing blueman
  pacman:
    name: blueman
    state: latest
  become: true

- name: Enabling Bluetooth service
  systemd:
    name: bluetooth
    state: started
    enabled: yes
  become: true
