- name: Installing Bluetooth Drivers & Apps
  pacman:
    name: 
      - bluez
      - bluez-utils
      - pulseaudio-bluetooth
      - blueman
    state: latest
  become: true

- name: Enabling Bluetooth service
  systemd:
    name: bluetooth
    state: started
    enabled: yes
  become: true
