- name: Installing Bluetooth Drivers & Apps
  pacman:
    name: 
      - bluez
      - bluez-utils
      - pulseaudio-bluetooth
      - blueman
      - bluedevil

    state: latest
  become: true

- name: Installing AUR Bluetooth Apps
  kewlfft.aur.aur:
    use: yay
    name: 
      - bluetuith
      # - bluez-rfcomm
    state: latest
  become: True
  become_user: aur_builder

- name: Enabling Bluetooth service
  systemd:
    name: bluetooth
    state: started
    enabled: yes
  become: true
