- name: Installing opencode
  pacman:
    name: opencode
    state: latest
  become: true

- name: Ensuring OpenCode config folder exists
  file:
    path: "{{ linux_user_home }}/.config/opencode"
    state: directory

# Check defaults/main.yml for the model variables used in the template.
- name: Deploying OpenCode config from template
  template:
    src: opencode.jsonc
    dest: "{{ linux_user_home }}/.config/opencode/opencode.jsonc"

- name: Copying OpenCode Skills folder
  copy:
    src: skills/
    dest: "{{ linux_user_home }}/.config/opencode/skills/"

- name: Copying OpenCode TUI config file (keybindings)
  copy:
    src: tui.jsonc
    dest: "{{ linux_user_home }}/.config/opencode/tui.jsonc"
