- name: Installing opencode
  pacman:
    name: opencode
    state: latest
  become: true

- name: Ensuring OpenCode config folder exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/opencode"
    state: directory

- name: Copying OpenCode Github Copilot config file
  copy:
    src: opencode-github-copilot.jsonc
    dest: "{{ ansible_facts['user_dir'] }}/.config/opencode/opencode-github-copilot.jsonc"

- name: Copying OpenCode Go config file
  copy:
    src: opencode-zen.jsonc
    dest: "{{ ansible_facts['user_dir'] }}/.config/opencode/opencode-zen.jsonc"

- name: Creating symlink to opencode.jsonc
  file:
    src: "{{ ansible_facts['user_dir'] }}/.config/opencode/opencode-zen.jsonc"
    dest: "{{ ansible_facts['user_dir'] }}/.config/opencode/opencode.jsonc"
    state: link

- name: Copying OpenCode Skills folder
  copy:
    src: skills/
    dest: "{{ ansible_facts['user_dir'] }}/.config/opencode/skills/"

- name: Copying OpenCode TUI config file (keybindings)
  copy:
    src: tui.jsonc
    dest: "{{ ansible_facts['user_dir'] }}/.config/opencode/tui.jsonc"
