- name: Installing Wayland tools and dependencies
  pacman:
    name:
      # Wayland is installed by sway
      - xorg-xwayland

      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk

      - qt5-wayland
      - qt6-wayland
      - libdecor # Recommended by SDL2

    state: latest
  become: true

- name: Installing Wayland AUR tools
  kewlfft.aur.aur:
    use: yay
    name:
      - wdisplays
      - glew-wayland # Maybe required by GLEW
    state: latest
  become: True
  become_user: aur_builder

- name: Copying Wayland GUI Libraries Compatibility Env Vars to ZSH import
  copy:
    src: export_wayland_gui_libraries_compatibility.zsh
    dest: "{{ ansible_env.HOME }}/.zshrc.d/"
