- name: Updated & Upgraded apt
  apt:
    update_cache: yes
    upgrade: yes
  become: true
  when: ansible_distribution | lower == 'ubuntu'

- name: Updated & Upgraded pacman
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: true
  when: ansible_distribution | lower == 'archlinux'
