- name: Update & Upgrade apt
  apt:
    update_cache: yes
    upgrade: yes
  become: true
  when: ansible_distribution | lower == 'ubuntu'

- name: Update & Upgrade pacman
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: true
  when: ansible_distribution | lower == 'archlinux'
