- name: Installing nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.5/install.sh | bash
  args:
    executable: /bin/bash
    chdir: ~

- name: Installing NodeJS
  shell: . ~/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
    chdir: ~
