- name: Installing Wireshark
  pacman:
    name: wireshark-qt
    state: latest
  become: True

- name: "Adding user '{{ linux_username }}' to 'wireshark' group"
  user:
    name: "{{ linux_username }}"
    groups: wireshark
    append: True
  become: True