- name: Installing dependency Gnome Keyring
  pacman:
    name: gnome-keyring
    state: latest
  become: true

- name: Ensuring SSH folder exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: Enabling and Starting GCR SSH Agent service
  systemd:
    name: gcr-ssh-agent.socket
    state: restarted
    enabled: yes
    scope: "user"
