- name: Deleting ZSH folder (if it exists)
  file:
    path: "{{ZSH_PATH}}"
    state: absent

- name: Installing ZSH
  pacman:
    name: zsh
    state: latest
  become: true

- name: Installing Oh-My-ZSH
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'

- name: Cloning zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ZSH_CUSTOM}}/plugins/zsh-autosuggestions"

- name: Cloning zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ZSH_CUSTOM}}/plugins/zsh-syntax-highlighting"

- name: Cloning zsh-vi-mode plugin
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode
    dest: "{{ZSH_CUSTOM}}/plugins/zsh-vi-mode"

- name: Installing Meslo Nerd Font for Powerlevel10k
  kewlfft.aur.aur:
    use: yay
    name: ttf-meslo-nerd-font-powerlevel10k
    state: latest
  become: true
  become_user: aur_builder

- name: Cloning powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: "{{ZSH_CUSTOM}}/themes/powerlevel10k"

- name: Changing default shell
  command: "chsh --shell $(command -v zsh) {{ linux_username }}"
  become: true

- name: Copying dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: zshrc
      dest: "{{ linux_user_home }}/.zshrc"
    - src: p10k.zsh
      dest: "{{ linux_user_home }}/.p10k.zsh"
    - src: modules/
      dest: "{{ linux_user_home }}/.zshrc.d/"
