- name: Installing picom
  pacman:
    name: picom
    state: latest
  become: true

- name: Copying picom config file
  copy:
    src: picom.conf
    dest: "{{ ansible_env.HOME }}/.config/picom.conf"
