- name: Installing Tailscale
  pacman:
    name: tailscale
    state: latest
  become: true

- name: Enabling and starting tailscaled service
  systemd:
    name: tailscaled.service
    state: started
    enabled: yes
  become: true

- name: Copying tailnet-connection service file
  template:
    src: tailnet-connection.service
    dest: /etc/systemd/system/tailnet-connection.service
  become: true

- name: Enabling and Starting tailnet-connection service
  systemd:
    name: tailnet-connection.service
    state: started
    enabled: yes
    daemon_reload: yes
  become: true

- name: Copying tailscale-systray service file
  copy:
    src: tailscale-systray.service
    dest: "{{ linux_user_home }}/.config/systemd/user/tailscale-systray.service"

- name: Enabling and Starting tailscale-systray service
  systemd:
    name: tailscale-systray.service
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes
