# Nautilus and xdg-utils stuff

- name: Installing Nautilus & xdg-utils (xdg-open)
  pacman:
    name:
      - nautilus
      - xdg-utils
    state: latest
  become: True

- name: Ensuring gtk3 bookmarks folder exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/gtk-3.0"
    state: directory

- name: Copying gtk3 bookmarks file
  copy:
    src: gtk3_bookmarks
    dest: "{{ ansible_facts['user_dir'] }}/.config/gtk-3.0/bookmarks"

- name: Configuring MIME Types default applications
  copy:
    src: mimeapps.list
    dest: "{{ ansible_facts['user_dir'] }}/.config/"

- name: Copying ZSH `xdg-open` aliases file
  copy:
    src: aliases_xdg_open.zsh
    dest: "{{ ansible_facts['user_dir'] }}/.zshrc.d/"

# Yazi stuff

- name: Installing Yazi and file previewer dependencies
  pacman:
    name:
      - yazi
      - ffmpegthumbnailer
      - 7zip
      - jq
      - poppler
      - fd
      - ripgrep
      - fzf
      - zoxide
      - imagemagick
    state: latest
  become: True

- name: Ensuring yazi config folder exists
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/yazi"
    state: directory


- name: Copying Yazi configuration file
  copy:
    src: yazi.toml
    dest: "{{ ansible_facts['user_dir'] }}/.config/yazi/yazi.toml"
