- name: Installing Nautilus & xdg-utils (xdg-open)
  pacman:
    name:
      - nautilus
      - xdg-utils
    state: latest
  become: True

- name: Ensuring gtk3 bookmarks folder exists
  file:
    path: "{{ ansible_env.HOME }}/.config/gtk-3.0"
    state: directory

- name: Copying gtk3 bookmarks file
  copy:
    src: gtk3_bookmarks
    dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/bookmarks"

- name: Configuring MIME Types default applications
  copy:
    src: mimeapps.list
    dest: "{{ ansible_env.HOME }}/.config/"

- name: Copying ZSH `xdg-open` aliases file
  copy:
    src: aliases_xdg_open.zsh
    dest: "{{ ansible_env.HOME }}/.zshrc.d/"



