- name: Installing OBS
  pacman:
    name: obs-studio
    state: latest
  become: true


- name: Copying OBS scenes folder
  copy:
    src: ./scenes
    dest: "{{ ansible_env.HOME }}/.config/obs-studio/basic/"
