- name: Installing rofi-wayland
  pacman:
    name: rofi-wayland
    state: latest
  become: true

- name: Copying rofi configuration files
  copy:
    src: config/
    dest: "{{ linux_user_home }}/.config/rofi/"
