- name: Installing rofi
  pacman:
    name: rofi
    state: latest
  become: true

- name: Ensuring rofi config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory

- name: Copying picom config file
  copy:
    src: config.rasi
    dest: "{{ ansible_env.HOME }}/.config/rofi/config.rasi"
