- name: Installed rofi
  pacman:
    name: rofi
    state: latest
  become: true

- name: Ensured rofi config directory
  file:
    path: ~/.config/rofi
    state: directory

- name: Copied picom config file
  copy:
    src: config.rasi
    dest: ~/.config/rofi/config.rasi
