- name: Installing rofi
  pacman:
    name: rofi
    state: latest
  become: true

- name: Ensuring rofi config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory

- name: Copying picom config folder
  copy:
    src: config/
    dest: "{{ ansible_env.HOME }}/.config/rofi/"
