# Arch Essentials:
- name: Installing Grub
  pacman:
    name: grub
    state: latest
  become: true

- name: Installing efibootmgr
  pacman:
    name: efibootmgr
    state: latest
  become: true

- name: Installing sudo
  pacman:
    name: sudo
    state: latest
  become: true

- name: Installing git
  pacman:
    name: git
    state: latest
  become: true

- name: Installing base
  pacman:
    name: base
    state: latest
  become: true

- name: Installing NetworkManager
  pacman:
    name: networkmanager
    state: latest
  become: true

# Drivers and stuff like that

- name: Installing android-file-transfer
  pacman:
    name: android-file-transfer
    state: latest
  become: true

# Video and Sound:
- name: Installing alsa-utils
  pacman:
    name: alsa-utils
    state: latest
  become: true

- name: Installing pavucontrol
  pacman:
    name: pavucontrol
    state: latest
  become: true

- name: Installing mpv
  pacman:
    name: mpv
    state: latest
  become: true

- name: Installing gwenview
  pacman:
    name: gwenview
    state: latest
  become: true

# Internet
- name: Installing net-tools
  pacman:
    name: net-tools
    state: latest
  become: True

- name: Installing KDE Connect
  pacman:
    name: kdeconnect
    state: latest
  become: true

- name: Installing OpenVPN
  pacman:
    name: openvpn
    state: latest
  become: true

- name: Installing Wireguard and dependecy openresolv
  pacman:
    name:
      - wireguard-tools
      - openresolv
    state: latest
  become: true

- name: Installing Tailscale
  pacman:
    name:
      - tailscale
    state: latest
  become: true

- name: Installing qBittorrent
  pacman:
    name: qbittorrent
    state: latest
  become: true

# Coding:
- name: Installing JDK
  pacman:
    name: jdk-openjdk
    state: latest
  become: true

# Utilities:
- name: Installing man pages
  pacman:
    name: man-db
    state: latest
  become: true

- name: Installing less
  pacman:
    name: less
    state: latest
  become: true

- name: Installing tree
  pacman:
    name: tree
    state: latest
  become: true

- name: Installing wget
  pacman:
    name: wget
    state: latest
  become: true

- name: Installing z
  pacman:
    name: z
    state: latest
  become: true

- name: Installing WoeUSB
  kewlfft.aur.aur:
   use: yay
   name: woeusb
   state: latest
  become: True
  become_user: aur_builder

- name: Installing android-tools
  pacman:
    name: android-tools
    state: latest
  become: true

- name: Installing scrcpy (Android Screen Share)
  pacman:
    name: scrcpy
    state: latest
  become: true

# - name: Installing wine, wine-gecko & wine-mono
#   pacman:
#     name:
#       - wine-stable
#       - wine-gecko
#       - wine-mono
#     state: latest
#   become: true
# 

# Apps:
- name: Installing Libre-Office
  pacman:
    name: libreoffice-still
    state: latest
  become: true

- name: Installing Discord
  pacman:
    name: discord
    state: latest
  become: true

- name: Installing Evince
  pacman:
    name: evince
    state: latest
  become: true

- name: Installing Obsidian
  pacman:
    name: obsidian
    state: latest
  become: true

- name: Installing Spotify
  kewlfft.aur.aur:
    use: yay
    name: spotify
    state: latest
  become: True
  become_user: aur_builder

- name: Installing Stremio
  kewlfft.aur.aur:
    use: yay
    name: stremio
    state: latest
  become: True
  become_user: aur_builder

- name: Installing Grayjay
  kewlfft.aur.aur:
    use: yay
    name: grayjay-bin
    state: latest
  become: True
  become_user: aur_builder

- name: Installing Slack
  kewlfft.aur.aur:
    use: yay
    name: slack-desktop
    state: latest
  become: True
  become_user: aur_builder

- name: Installing Inkscape
  pacman:
    name: inkscape
    state: latest
  become: true

- name: Installing Gnome Calculator
  pacman:
    name: gnome-calculator
    state: latest
  become: true

- name: Installing NumWorks
  kewlfft.aur.aur:
   use: yay
   name: numworks-epsilon
   state: latest
  become: True
  become_user: aur_builder

# - name: Installing Steam
#   pacman:
#     name: steam
#     state: latest
#   become: true
# 
