# Arch Essentials:
- name: Installing Grub
  pacman:
    name: grub
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing efibootmgr
  pacman:
    name: efibootmgr
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing sudo
  pacman:
    name: sudo
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing git
  pacman:
    name: git
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing base
  pacman:
    name: base
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing NetworkManager
  pacman:
    name: networkmanager
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

# Video and Sound:
- name: Installing alsa-utils
  pacman:
    name: alsa-utils
    state: latest
  become: true
  tags:
    - MINIMAL_GUI
    - GUI

- name: Installing pavucontrol
  pacman:
    name: pavucontrol
    state: latest
  become: true
  tags:
    - MINIMAL_GUI
    - GUI

- name: Installing vlc
  pacman:
    name: vlc
    state: latest
  become: true
  tags:
    - GUI

- name: Installing gwenview
  pacman:
    name: gwenview
    state: latest
  become: true
  tags:
    - GUI

# Internet
- name: Installing net-tools
  pacman:
    name: net-tools
    state: latest
  become: True
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing KDE Connect
  pacman:
    name: kdeconnect
    state: latest
  become: true
  tags:
    - GUI

- name: Installing OpenVPN
  pacman:
    name: openvpn
    state: latest
  become: true
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

    # - name: Installing ProtonVPN
    #   kewlfft.aur.aur:
    #     use: yay
    #     name: protonvpn-cli
    #     state: latest
    #   become: True
    #   become_user: aur_builder
    #   tags:
    #     - TUI
    #     - MINIMAL_GUI
    #     - GUI

# Coding:
- name: Installing vim
  pacman:
    name: vim
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing JDK
  pacman:
    name: jdk-openjdk
    state: latest
  become: true
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

# Utilities:
- name: Installing man pages
  pacman:
    name: man-db
    state: latest
  become: true
  tags:
    - MINIMAL_TUI
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing less
  pacman:
    name: less
    state: latest
  become: true
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing tree
  pacman:
    name: tree
    state: latest
  become: true
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing wget
  pacman:
    name: wget
    state: latest
  become: true
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing z
  pacman:
    name: z
    state: latest
  become: true
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing Gnome Calculator
  pacman:
    name: gnome-calculator
    state: latest
  become: true
  tags:
    - GUI

- name: Installing NumWorks
  kewlfft.aur.aur:
   use: yay
   name: numworks-epsilon
   state: latest
  become: True
  become_user: aur_builder
  tags:
    - GUI

# - name: Installing wine, wine-gecko & wine-mono
#   pacman:
#     name:
#       - wine-stable
#       - wine-gecko
#       - wine-mono
#     state: latest
#   become: true
#   tags:
#     - GUI

# Apps:
- name: Installing Google Chrome
  kewlfft.aur.aur:
   use: yay
   name: google-chrome
   state: latest
  become: True
  become_user: aur_builder
  tags:
    - GUI

- name: Installing Libre-Office
  pacman:
    name: libreoffice-still
    state: latest
  become: true
  tags:
    - GUI

- name: Installing Discord
  pacman:
    name: discord
    state: latest
  become: true
  tags:
    - GUI

- name: Installing Okular
  pacman:
    name: okular
    state: latest
  become: true
  tags:
    - GUI

- name: Installing Obsidian
  pacman:
    name: obsidian
    state: latest
  become: true
  tags:
    - GUI

- name: Installing Spotify
  kewlfft.aur.aur:
    use: yay
    name: spotify
    state: latest
  become: True
  become_user: aur_builder
  tags:
    - GUI

- name: Installing Slack
  kewlfft.aur.aur:
    use: yay
    name: slack-desktop
    state: latest
  become: True
  become_user: aur_builder
  tags:
    - GUI

- name: Installing Figma
  kewlfft.aur.aur:
    use: yay
    name: figma-linux
    state: latest
  become: True
  become_user: aur_builder
  tags:
    - GUI

# - name: Installing Steam
#   pacman:
#     name: steam
#     state: latest
#   become: true
#   tags:
#     - GUI

# Others:
- name: Installing Gnome Keyring
  pacman:
    name: gnome-keyring
    state: latest
  become: true
  tags:
    - TUI
    - MINIMAL_GUI
    - GUI

- name: Installing seahorse (Gnome Keyring GUI)
  pacman:
    name: seahorse
    state: latest
  become: true
  tags:
    - GUI
