# Arch Essentials:
- name: Installing Grub
  pacman:
    name: grub
    state: latest
  become: true

- name: Installing efibootmgr
  pacman:
    name: efibootmgr
    state: latest
  become: true

- name: Installing sudo
  pacman:
    name: sudo
    state: latest
  become: true

- name: Installing git
  pacman:
    name: git
    state: latest
  become: true

- name: Installing base
  pacman:
    name: base
    state: latest
  become: true

- name: Installing NetworkManager
  pacman:
    name: networkmanager
    state: latest
  become: true

# Video and Sound:
- name: Installing alsa-utils
  pacman:
    name: alsa-utils
    state: latest
  become: true

- name: Installing pavucontrol
  pacman:
    name: pavucontrol
    state: latest
  become: true

- name: Installing pulseaudio
  pacman:
    name: pulseaudio
    state: latest
  become: true

- name: Installing vlc
  pacman:
    name: vlc
    state: latest
  become: true

# Internet
- name: Installing RealVNC Server
  pacman:
    executable: yay
    name: realvnc-vnc-server
    state: latest

- name: Installing RealVNC Viewer
  pacman:
    executable: yay
    name: realvnc-vnc-viewer
    state: latest

- name: Installing KDE Connect
  pacman:
    name: kdeconnect
    state: latest
  become: true

# Coding:
- name: Installing vim
  pacman:
    name: vim
    state: latest
  become: true

- name: Installing VS Code
  pacman:
    executable: yay
    name: visual-studio-code-bin
    state: latest
  become: true

# - name: Installing nvm
#   pacman:
#     executable: yay
#     name: nvm
#     state: latest

# - name: Installing Android Studio
#   pacman:
#     executable: yay
#     name: android-studio
#     state: latest

# Utilities:

- name: Installing wget
  pacman:
    name: wget
    state: latest
  become: true

# - name: Installing wine, wine-gecko & wine-mono
#   pacman:
#     name:
#       - wine-stable
#       - wine-gecko
#       - wine-mono
#     state: latest
#   become: true

# Apps:
- name: Installing Firefox
  pacman:
    name: firefox
    state: latest
  become: true

- name: Installing Spotify
  pacman:
    executable: yay
    name: spotify
    state: latest

- name: Installing Discord
  pacman:
    name: discord
    state: latest
  become: true

- name: Installing Slack
  pacman:
    executable: yay
    name: slack-desktop
    state: latest

- name: Installing Figma
  pacman:
    executable: yay
    name: figma-linux
    state: latest

# - name: Installing Steam
#   pacman:
#     name: steam
#     state: latest
#   become: true

# Others:
- name: Installing Deja Dup
  pacman:
    name: deja-dup
    state: latest
  become: true

- name: Installing Gnome Keyring & seahorse
  pacman:
    name:
      - gnome-keyring
      - seahorse
    state: latest
  become: true
