- name: Installing python-pip
  pacman:
    name: python-pip
    state: latest
  become: true

- name: Installing BlackboardSync
  pip:
    name: blackboardsync
    state: latest
    break_system_packages: true

- name: Copying config file
  copy:
    src: "blackboard_sync"
    dest: "{{ ansible_env.HOME }}/.config/blackboard_sync"

- name: Ensuring destination folder exists
  file:
    path: "{{ ansible_env.HOME }}/Documents/Universidade_BB"
    state: directory
