- name: Installing Flatpak
  pacman:
    name: flatpak
    state: latest
  become: true

- name: Installing BlackboardSync
  flatpak:
    name: app.bbsync.BlackboardSync
    state: present

- name: Ensuring config folder exists
  file:
    path: "{{ ansible_env.HOME }}/.var/app/app.bbsync.BlackboardSync/config/"
    state: directory

- name: Copying config file
  copy:
    src: "blackboard_sync"
    dest: "{{ ansible_env.HOME }}/.var/app/app.bbsync.BlackboardSync/config/blackboard_sync"

- name: Ensuring destination folder exists
  file:
    path: "{{ ansible_env.HOME }}/Documents/Universidade_BB"
    state: directory
