- name: Installing Foot terminal emulator
  pacman:
    name: foot
    state: latest
  become: true

- name: Ensuring config folder exists
  file:
    path: "{{ linux_user_home }}/.config/foot"
    state: directory

- name: Copying Foot config file
  copy:
    src: foot.ini
    dest: "{{ linux_user_home }}/.config/foot/foot.ini"
