- name: Installing docker & docker-compose
  pacman:
    name:
      - docker
      - docker-compose
    state: latest
  become: true

- name: "Adding user '{{ user }}' to 'docker' group"
  user:
    name: "{{ user }}"
    groups: docker
    append: True
  become: True
  