- name: Installing docker & docker-compose
  pacman:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: latest
  become: true

- name: "Adding user '{{ linux_username }}' to 'docker' group"
  user:
    name: "{{ linux_username }}"
    groups: docker
    append: True
  become: True
  