- name: Installing vim
  pacman:
    name: vim
    state: latest
  become: true

- name: Ensuring `~/.vim` directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: directory
    mode: '0755'

- name: Copying `.vimrc` file to ~/.vim
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0755'

- name: Copying `autoload` folder to ~/.vim
  copy:
    src: autoload/
    dest: "{{ ansible_env.HOME }}/.vim/autoload/"
    mode: '0755'

- name: Copying `backup` folder to ~/.vim
  copy:
    src: backup/
    dest: "{{ ansible_env.HOME }}/.vim/backup/"
    mode: '0755'

- name: Copying `colors` folder to ~/.vim
  copy:
    src: colors/
    dest: "{{ ansible_env.HOME }}/.vim/colors/"
    mode: '0755'

- name: Copying `plugged` folder to ~/.vim
  copy:
    src: plugged/
    dest: "{{ ansible_env.HOME }}/.vim/plugged/"
    mode: '0755'