- name: Installing vim
  pacman:
    name: vim
    state: latest
  become: true

- name: Ensuring `~/.vim` directory exists
  file:
    path: "{{ linux_user_home }}/.vim"
    state: directory
    mode: '0755'

- name: Copying `.vimrc` file to ~/.vim
  copy:
    src: .vimrc
    dest: "{{ linux_user_home }}/.vimrc"
    mode: '0755'

# - name: Copying `autoload` folder to ~/.vim
#   copy:
#     src: autoload/
#     dest: "{{ linux_user_home }}/.vim/autoload/"
#     mode: '0755'

# - name: Copying `backup` folder to ~/.vim
#   copy:
#     src: backup/
#     dest: "{{ linux_user_home }}/.vim/backup/"
#     mode: '0755'

# - name: Copying `colors` folder to ~/.vim
#   copy:
#     src: colors/
#     dest: "{{ linux_user_home }}/.vim/colors/"
#     mode: '0755'

# - name: Copying `plugged` folder to ~/.vim
#   copy:
#     src: plugged/
#     dest: "{{ linux_user_home }}/.vim/plugged/"
#     mode: '0755'