- name: Installing Alacritty
  pacman:
    name: alacritty
    state: latest
  become: true

- name: Ensuring config folder exists
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory

- name: Copying Alacritty @{{ target_environment }} config file
  copy:
    src: "{{ target_environment }}@alacritty.toml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
