- name: Installing Alacritty
  pacman:
    name: alacritty
    state: latest
  become: true

- name: Ensuring config folder exists
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory

- name: Copying Alacritty config file
  copy:
    src: alacritty.toml
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
