# System fonts - are fonts that are set as the default ones to the system
# All the apps should use this fonts by default based on the fontconfig file

- name: Installing system fonts
  pacman:
    name:
      - fontconfig
      - inter-font
      - noto-fonts
      - noto-fonts-emoji
      - ttf-dejavu
      - ttf-liberation
      - ttf-fira-code
      - ttf-nerd-fonts-symbols
    state: latest
  become: true

- name: Ensuring fontconfig config directory exists
  file:
    path: "{{ linux_user_home }}/.config/fontconfig"
    state: directory

- name: Copying fontconfig aliases
  copy:
    src: fonts.conf
    dest: "{{ linux_user_home }}/.config/fontconfig/fonts.conf"

- name: Refreshing font cache
  command: fc-cache -f
  changed_when: false

# User fonts - this are not default fonts, but are useful for some applications (LibreOffice, Word, Gimp, ...)
# Add new fonts by appending an entry on the packages or a (name + url) to the loop below

- name: Installing user fonts
  kewlfft.aur.aur:
   use: yay
   name:
      - ttf-d-din
      - ttf-poppins
   state: latest
  become: True
  become_user: aur_builder

- name: Ensuring user fonts directory exists
  file:
    path: "{{ linux_user_home }}/.local/share/fonts"
    state: directory

- name: Downloading user fonts
  get_url:
    url: "{{ item.url }}"
    dest: "{{ linux_user_home }}/.local/share/fonts/{{ item.name }}"
  loop:
    - name: JUST_NOVA-Regular.ttf
      url: https://justachange.pt/wp-content/themes/just-theme/fonts/JUST_NOVA-Regular.ttf

- name: Refreshing font cache
  command: fc-cache -f
  changed_when: false
