- name: Installing qt6ct, lxappearance, glib, dconf
  pacman:
    name:
      - qt6ct
      - lxappearance
      - glib2
      - dconf
    state: latest
  become: true

- name: Installing Papirus icon theme, breeze
  pacman:
    name:
      - papirus-icon-theme
      - breeze
    state: latest
  become: true

- name: Getting user UID
  command: id -u
  register: user_uid

- name: Setting GNOME (gsettings) dark mode
  command: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ user_uid.stdout }}/bus"

- name: Ensuring qt6ct config folder exists
  file:
    path: "{{ ansible_env.HOME }}/.config/qt6ct"
    state: directory

- name: Copying qt6ct config file
  copy:
    src: qt6ct.conf
    dest: "{{ ansible_env.HOME }}/.config/qt6ct/qt6ct.conf"

- name: Copying GTK2 config file
  copy:
    src: "gtkrc-2.0"
    dest: "{{ ansible_env.HOME }}/.gtkrc-2.0"

- name: Ensuring GTK3 config folder exists
  file:
    path: "{{ ansible_env.HOME }}/.config/gtk-3.0"
    state: directory

- name: Copying GTK3 config file
  copy:
    src: gtk3_settings.ini
    dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"

- name: Copying Appearance Env Vars to ZSH import
  copy:
    src: export_appearance.zsh
    dest: "{{ ansible_env.HOME }}/.zshrc.d/"
