- name: Updated & Upgraded pacman
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Installed ansible's packages dependencies
  pacman:
    name:
      - python-setuptools
      - python-lxml
    state: latest
  become: true
