- name: Updating & Upgrading pacman
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Installing ansible's packages dependencies
  pacman:
    name:
      - python-setuptools
      - python-lxml
    state: latest
  become: true

- name: Ensuring .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Ensuring dotfiles config file exists
  file:
    path: "{{ ansible_env.HOME }}/.config/dotfiles_config"
    state: touch

- name: Writing dotfiles environment at config file
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/dotfiles_config"
    regexp: '^ENV='
    line: "ENV={{ target_environment }}"
