- name: Installed Syncthing
  pacman:
    name: syncthing
    state: latest
  become: true

- name: Enabled and Started service
  ansible.builtin.systemd:
    name: "syncthing"
    state: restarted
    enabled: yes
    scope: "user"

# From https://github.com/eddyhub/ansible-syncthing/blob/master/tasks/main.yml

- name: Waited for config file (toke some time)
  wait_for: path=~/.config/syncthing/config.xml

- name: Set private WebInterface address
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/gui/address
    value: "{{ private_address }}"

- name: Set listen address
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/options/listenAddress
    value: "{{ listen_address }}"

- name: Set localAnnounceEnabled
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/options/localAnnounceEnabled
    value: "{{ local_announce | lower }}"

- name: Set globalAnnounceEnabled
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/options/globalAnnounceEnabled
    value: "{{ global_announce | lower }}"

- name: Set login user
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/gui/user
    value: "{{ syncthing_gui_user }}"
  when: syncthing_gui_user is defined

- name: Set login password
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/gui/password
    value: "{{ syncthing_gui_password }}"
  when: syncthing_gui_password is defined

- name: Deleted Default Folder
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/folder[@id="default"]
    state: absent

- name: Changed folder defaults update order
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/defaults/folder/order
    value: smallestFirst

- name: Removed all devices defaults addresses
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/defaults/device/address
    state: absent

- name: Added devices defaults addresses
  xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/defaults/device
    add_children:
      - address: tcp://192.168.1.70:22000
      - address: tcp://192.168.1.71:22000
      - address: tcp://192.168.1.72:22000
      - address: tcp://192.168.1.73:22000
      - address: tcp://192.168.1.74:22000
      - address: tcp://192.168.1.75:22000
      - address: tcp://dsgdevbraga.ddns.net:22000
      - address: dynamic

- name: Restarted service
  ansible.builtin.systemd:
    name: "syncthing"
    state: restarted
    scope: "user"
