- name: Installing Syncthing
  pacman:
    name: syncthing
    state: latest
  become: true

- name: Enabling and Starting service
  systemd:
    name: "syncthing"
    state: restarted
    enabled: yes
    scope: "user"

# From https://github.com/eddyhub/ansible-syncthing/blob/master/tasks/main.yml

- name: Waiting for config file (toke some time)
  wait_for: path="{{ ansible_env.HOME }}/.config/syncthing/config.xml"

- name: Setting private WebInterface address
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/gui/address
    value: "{{ private_address }}"

- name: Setting listen address
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/listenAddress
    value: "{{ listen_address }}"

- name: Setting localAnnounceEnabled
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/localAnnounceEnabled
    value: "{{ local_announce | lower }}"

- name: Setting globalAnnounceEnabled
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/globalAnnounceEnabled
    value: "{{ global_announce | lower }}"

- name: Setting login user
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/gui/user
    value: "{{ syncthing_gui_user }}"
  when: syncthing_gui_user is defined

- name: Setting login password
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/gui/password
    value: "{{ syncthing_gui_password }}"
  when: syncthing_gui_password is defined

- name: Deleting Default Folder
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/folder[@id="default"]
    state: absent

- name: Changing folder defaults update order
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/defaults/folder/order
    value: smallestFirst

- name: Removing all devices defaults addresses
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/defaults/device/address
    state: absent

- name: Adding devices defaults addresses
  xml:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/defaults/device
    add_children:
      - address: tcp://192.168.1.70:22000
      - address: tcp://192.168.1.71:22000
      - address: tcp://192.168.1.72:22000
      - address: tcp://192.168.1.73:22000
      - address: tcp://192.168.1.74:22000
      - address: tcp://192.168.1.75:22000
      - address: tcp://dsgdevbraga.ddns.net:22000
      - address: dynamic

- name: Restarting service
  systemd:
    name: "syncthing"
    state: restarted
    scope: "user"

- name: Installing Syncthing Tray
  kewlfft.aur.aur:
    use: yay
    name:
      - "c++utilities"
      - "qtforkawesome"
      - "syncthingtray"
    state: latest
  become: True
  become_user: aur_builder
